### ISSUE TITLE
SignalExceptionHandler打了断点，并没有拦截到异常

### ISSUE THREAD

**Issue by NiceShock** [oncezw/CrashX#1]
xcode11，swift5是不是已经无法通过信号的方式捕获异常了

**Comment by WEzou** [comment]
> xcode11，swift5是不是已经无法通过信号的方式捕获异常了

这个工程并不是拦截异常，它的作用是收集crash。所以不能通过debug的方式拦截。正确的调试方式是运行在真机上，然后尝试让其闪退，再次debug的时候，主动执行readAllCrashInfo() ，你就可以看到之前的crash日志，然后根据日志做你想做的。

**Comment by oncezw** [comment]
@NiceShock 
这个工程并不是拦截异常，它的作用是收集crash。所以不能通过debug的方式拦截。正确的调试方式是运行在真机上，然后尝试让其闪退，再次debug的时候，主动执行readAllCrashInfo() ，你就可以看到之前的crash日志，然后根据日志做你想做的。

**Comment by NiceShock** [comment]
我的目的也不是拦截异常，我看了demo，是通过信号的方式得知应用要崩溃了，我在xcode11，swift5的环境下，真机测试了debug模式还有release模式都无法获得crash日志。所以我怀疑swift5信号不能正常的接收了

**Comment by NiceShock** [comment]
可以捕获到了，我发现崩溃的时候不能联调，否则无法保存crash日志

**Comment by oncezw** [comment]
@NiceShock ok，that’s great!
